name: CI - Build and Test Pacman

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GCC and Make
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Build Pacman
        run: |
          echo "Compilando com Makefile..."
          make

      - name: Run Unity tests
        run: |
          if [ -d tests ]; then
            echo "Pasta tests/ encontrada. Executando make test..."
            make test
          else
            echo "Nenhum teste encontrado. Prosseguindo..."
          fi
